### ISSUE TITLE
Move meetup attendance data into DB

### ISSUE THREAD

**Issue by asgrim** [phphants/phph-site#113]
Move the meetup attendance data into the database.
The user will be able to see all the meetups they've attended, and therefore view Joind.in links, video links etc. that are relevant to them.
Depends on #100. Also depends on #102.

**Comment by asgrim** [comment]
I'd like to be able to import attendance data from Eventbrite but not sure how easy that will be. It'd mean basically creating accounts for everyone who has attended, but we'd need to send a password reset email so they can activate their login. Thoughts @lboynton @MrNorm @jezemery ?

**Comment by jezemery** [comment]
@asgrim most attendees have Twitter right? Couldn't you create an account based on twitter handle, and then people don't actually need accounts specifically?

**Comment by asgrim** [comment]
I already plan on implementing Twitter login ;) #144 (as well as github, facebook and maybe Meetup)

**Comment by jezemery** [comment]
Another thought. ( because I hate auto-enrollment ). Eventbrite gives email & name right? So put all names etc up on the site with stats, and then allow people to "claim" their spot using email?

**Comment by asgrim** [comment]
So, basically have a DB table with all the EB attendance; when a user registers, it shows them their EB attendance records, and then they can "import" that? Seems like a reasonable approach. I agree, not a fan of the auto enrolment idea either, although to attend they'll need an account in one form or another (whether it's an third party login or otherwise), but yes; I like that idea! Let's roll with that.

**Comment by asgrim** [comment]
I don't think this is worth doing; if people want to mark events in the past they attended, they can.
