### ISSUE TITLE
Add link to #phphants Slack on phpug

### ISSUE THREAD

**Issue by asgrim** [phphants/phph-site#136]
Link: https://phpug.slack.com/
Invitations: http://murmuring-forest-7062.herokuapp.com/

**Comment by asgrim** [comment]
@heiglandreas how likely is it that the invitations link above will change please?

**Comment by heiglandreas** [comment]
I have no intention of changing the link. Should heroku change it though I'd try to remember that you need to update it :)

Alternatively you can also use https://slofile.com/slack/phpug which also is a link from an external platform that *might* change. 

Perhaps I should add an endpoint at php.ug itself...

**Comment by asgrim** [comment]
Thanks for feedback there @heiglandreas :)

**Comment by heiglandreas** [comment]
Should have mentioned here that there are now endpoints right at php.ug - http://slack.php.ug to get to the slack and https://php.ug/slackinvite to get an invitation to the slack.

**Comment by asgrim** [comment]
That's what I've added, thanks @heiglandreas :)

**Comment by heiglandreas** [comment]
I gave you those links via a different channel and just wanted to add them here for completion and future reference :) Thanks for linking at phphants!
