### ISSUE TITLE
Content not appearing in IE11 

### ISSUE THREAD

**Issue by lboynton** [phphants/phph-site#157]
Normally I would say ignore IE, but we had someone mention this at the meet up last time.

![bs_win10_ie_11 0](https://cloud.githubusercontent.com/assets/98873/21999917/749a8fb8-dc34-11e6-93d5-b2bdc027b342.jpg)

**Comment by asgrim** [comment]
:O

**Comment by ChiefWigs1982** [comment]
I think you'd need to change `.content {flex:1;}` to .content `{flex: 1 0 auto;}` for flex to work properly in IE - other browsers should read that fine too...

**Comment by lboynton** [comment]
Thanks @ChiefWigs1982, I think you're right!
