### ISSUE TITLE
Double escaping for talks?

### ISSUE THREAD

**Issue by asgrim** [phphants/phph-site#172]
`Test Strategies &amp;&amp; Process — (by Owen Beresford)`

possibly double escaping somewhere; investigate and fix dis

**Comment by doctor-data** [comment]
He who found it, fixes it @lboynton

**Comment by asgrim** [comment]
Fixed this by hand; wasn't double-escape, was just the data was already stored escaped for some reason. Checked for any other obvious cases too.
