### ISSUE TITLE
Cannot add a new events

### ISSUE THREAD

**Issue by jezemery** [phphants/phph-site#204]
One of the recent PRs has broken the ability to add new events, I need to look at and resolve this.
Also would be good to add test for this issue.

**Comment by jezemery** [comment]
Looks like this is only an issue if you log out of Twitter, once having logged in via Twitter...

**Comment by asgrim** [comment]
Huh, interesting. If you're already authenticated there's no reason it calls back to Twitter, so not sure why logging out should affect this. I'll see if I can check this out and reproduce locally.

Workaround: don't log out of Twitter (I mean, why would you?? :smile: )

**Comment by asgrim** [comment]
Hmm, I can't seem to reproduce this locally... could you give me some more information please when you get a chance?
