### ISSUE TITLE
Looking for speakers section obscured on mobile

### ISSUE THREAD

**Issue by lboynton** [phphants/phph-site#76]
See screenshot

![phph-responsive-issue](https://cloud.githubusercontent.com/assets/98873/8627380/954ba2c2-2742-11e5-996e-051b08b11996.png)

**Comment by asgrim** [comment]
@zaccolley can you fix this please? ;)

**Comment by asgrim** [comment]
Because @lboynton is too "busy" (doing nothing)

**Comment by lboynton** [comment]
I really am busy (doing nothing)

**Comment by zaccolley** [comment]
on it friends :+1:

**Comment by zaccolley** [comment]
sorry about all the spam, i was trying to (force :scream:)  push without the whitespace changes (you cant see the changed code changed!) haha

**Comment by lboynton** [comment]
Wow @zaccolley thanks for looking at this so soon! So much quicker than me!

**Comment by zaccolley** [comment]
if you can check against some different devices that'd be good

**Comment by lboynton** [comment]
Will take a look soon :)

**Comment by lboynton** [comment]
I see why you've done it this way, but my only slight concern is the footer on the contact page looks rather big. Maybe some [flexbox](https://philipwalton.github.io/solved-by-flexbox/demos/sticky-footer/) magic might be better?
![phph-site-footer](https://cloud.githubusercontent.com/assets/98873/13070047/29643802-d481-11e5-9634-bca47a4cb7ed.png)

**Comment by zaccolley** [comment]
Yeaaah, that'd work nicely.

What the site's browser usage? Flexbox isn't supported everywhere, but it's pretty good: http://caniuse.com/#search=flexbox

**Comment by lboynton** [comment]
I'm happy with the browser support, @asgrim?

**Comment by asgrim** [comment]
Considering our target audience, I think we should be fine

**Comment by zaccolley** [comment]
cool will do this tonight :+1:
