### ISSUE TITLE
Videos page very slow

### ISSUE THREAD

**Issue by zaccolley** [phphants/phph-site#84]
http://phphants.co.uk/videos

video page is very slow, makes it unusable on my laptop.

I think lazy loading the youtube vids in would fix this to remove any blocking scripts.

**Comment by lboynton** [comment]
Also some of the videos at the bottom of the page ask me to sign in to view them. @asgrim?

**Comment by asgrim** [comment]
@lboynton which ones in particular?

**Comment by lboynton** [comment]
- HOW TO DEVELOP YOUR DEVELOPMENT OF BEING A DEVELOPER WITHOUT DOING ANY DEVELOPMENT
- PHP and Enums
- Errors, Exceptions and Logging
- Composer Tutorial
- PHP FIG: Standardising PHP

**Comment by asgrim** [comment]
@lboynton thanks, the privacy settings were too extreme

**Comment by zaccolley** [comment]
my PR needs testing, have only checked in chrome ubuntu

**Comment by zaccolley** [comment]
will ch-ch-check it out in a few different places
